apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels: 
    name: spring-boot-app
spec:
  replicas: 2
  selector:
    matchlabels:
      name: spring-boot-app
  templet:
    matadata: 
      labels: 
        name: spring-boot-app
    spec:
      containers: 
        name: spring-boot-app
        imahe: nagakrishna95/ultimate-cicd:35
        ports:
          containerport: 8080
      
    
