apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels: 
    name: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: spring-boot-app
  template:
    metadata: 
      labels: 
        name: spring-boot-app
    spec:
      containers: 
        name: spring-boot-app
        image: nagakrishna95/ultimate-cicd:35
        ports:
          containerPort: 8080
      
    
