apiVersion: app/v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocal: tcp
  selector:
    app: spring-boot-app



    
